# Generated by Django 4.2.6 on 2023-10-14 07:04

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=127, verbose_name="Название")),
                ("quantity", models.IntegerField(default=0, verbose_name="Количество")),
                (
                    "image",
                    models.ImageField(
                        default="product_images/Заглушка фото карточки товара.png",
                        max_length=511,
                        upload_to=apps.core.models.product_image_upload_path,
                        verbose_name="Выбрать изображение",
                    ),
                ),
                (
                    "is_visible",
                    models.BooleanField(default=True, verbose_name="Отображается?"),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
                "db_table": "product",
            },
        ),
    ]
