# Generated by Django 4.2.6 on 2023-10-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="price",
            field=models.FloatField(default=0, verbose_name="Цена"),
        ),
    ]
