# Generated by Django 4.2.6 on 2023-10-14 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_productmodel_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_id", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepare", "Готовится"),
                            ("delivery", "доставляется"),
                            ("arrived", "Ожидание"),
                            ("finished", "Завершен"),
                        ],
                        default="prepare",
                        max_length=12,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(max_length=127, verbose_name="Адрес доставки"),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата заказа"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата получения",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Стоимость")),
                ("code", models.CharField(max_length=6, verbose_name="Код")),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "order",
            },
        ),
    ]
