# Generated by Django 4.2.6 on 2023-10-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_ordermodel_status_order2productmodel"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Order2ProductModel",
            new_name="OrderToProductModel",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="products",
            field=models.ManyToManyField(
                through="core.OrderToProductModel",
                to="core.productmodel",
                verbose_name="Продукты",
            ),
        ),
    ]
