# Generated by Django 4.2.6 on 2023-10-14 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_order2productmodel_ordertoproductmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="delivery_address",
            field=models.CharField(
                blank=True, max_length=127, null=True, verbose_name="Адрес доставки"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("prepare", "Готовится"),
                    ("ready", "Ожидает доставки"),
                    ("delivery", "Доставляется"),
                    ("arrived", "Ожидание"),
                    ("finished", "Завершен"),
                ],
                default="prepare",
                max_length=12,
                verbose_name="Статус",
            ),
        ),
    ]
