# Generated by Django 4.2.6 on 2023-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_ordermodel_delivery_address_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="end_date",
            new_name="finish_date",
        ),
    ]
