services:
  fastapi:
    build:
      context: ./src/backend/
    env_file:
      - .env-dev
    container_name: fastapi
    command: ["bash", "start.sh"]
    restart: always
    ports:
      - 8080:8080
  django:
    build: 
      context: ./src/server/
    env_file:
      - .env-dev
    container_name: django
    restart: always
    ports:
      - 8000:8000
    
  bot:
    build: 
      context: ./src/tg
    container_name: bot
    