# Generated by Django 4.2.6 on 2023-10-13 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order2ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
            ],
            options={
                "verbose_name": "Заказ к модификации товара",
                "verbose_name_plural": "Заказ к модификациям товаров",
                "db_table": "order__order2modification",
            },
        ),
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "delivery_address",
                    models.CharField(
                        blank=True,
                        max_length=511,
                        null=True,
                        verbose_name="Адрес доставки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создан"),
                            ("baked", "Готовится"),
                            ("in_delivery", "В доставке"),
                            ("received", "Получен"),
                        ],
                        default="created",
                        max_length=32,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата заказа"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Дата получения",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Стоимость")),
                (
                    "products",
                    models.ManyToManyField(
                        through="orders.Order2ProductModel",
                        to="products.productmodel",
                        verbose_name="Продукты",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "db_table": "order__order",
            },
        ),
        migrations.AddField(
            model_name="order2productmodel",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.ordermodel",
                verbose_name="Заказ",
            ),
        ),
        migrations.AddField(
            model_name="order2productmodel",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.productmodel",
                verbose_name="Модификация продукта",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="order2productmodel",
            unique_together={("order", "product")},
        ),
    ]
