# Generated by Django 4.2.6 on 2023-10-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="usermodel",
            name="code",
            field=models.CharField(default="", max_length=50, verbose_name="code"),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="is_confirmed"),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="telegram_id",
            field=models.CharField(
                max_length=127, unique=True, verbose_name="telegram id"
            ),
        ),
    ]
