# Generated by Django 4.2.6 on 2023-10-14 11:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_adminmodel_usermodel_code_usermodel_is_verified_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usermodel",
            old_name="is_verified",
            new_name="is_confirmed",
        ),
        migrations.RenameField(
            model_name="usermodel",
            old_name="date_joined",
            new_name="joined",
        ),
    ]
